# Generated by Django 5.2.4 on 2025-07-13 15:50

from django.db import migrations, models


def clear_default_avatars(apps, schema_editor):
    """
    Set avatar to NULL for users that have the old default avatar path.
    """
    CustomUser = apps.get_model('authentication', 'CustomUser')
    CustomUser.objects.filter(avatar='assets/img/added-images/default.png').update(avatar=None)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.RunPython(clear_default_avatars, migrations.RunPython.noop),
    ]
