# Generated by Django 5.2.4 on 2025-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='assets/img/added-images/default.png', null=True, upload_to='avatars/'),
        ),
    ]
