# Generated by Django 5.2.4 on 2025-07-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_default_avatar'),
        ('authentication', '0003_alter_customuser_avatar'),
    ]

    operations = [
    ]
