# Generated by Django 5.2.4 on 2025-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_trackedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
