# Generated by Django 5.2.4 on 2025-07-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
