# Generated by Django 5.2.4 on 2025-07-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='social_facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_twitter',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
