# Generated by Django 5.2.4 on 2025-07-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_social_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registered_at',
        ),
    ]
