# Generated by Django 5.2.4 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_customuser_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
