# Generated by Django 5.2.4 on 2025-07-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vcard_include_bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vcard_include_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vcard_include_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vcard_include_website',
            field=models.BooleanField(default=True),
        ),
    ]
